normalized naming between 'host' and 'server'; setup as systemd service for better robustness

diff --git a/src/terraform/main.tf.yaml b/src/terraform/main.tf.yaml
--- a/src/terraform/main.tf.yaml
+++ b/src/terraform/main.tf.yaml
@@ -14,7 +14,7 @@ variable:
     description: Path to the credentials file.
     type: string
     nullable: false
-  image:
+  host_image:
     description: Reference to base image.
     type: string
     nullable: false
@@ -39,9 +39,9 @@ variable:
     type: string
     default: us-central1
     nullable: false
-  server_name:
-    description: Name of the minecraft server.
-    default: minecraft-server
+  host_name:
+    description: Name of cloudcraft's minecraft server.
+    default: cloudcraft-host
     nullable: false
   server_type:
     description: Takes 'java' or 'bedrock'.
@@ -54,9 +54,12 @@ variable:
     nullable: false
 
 locals:
-  docker_image: '${var.server_type == "bedrock" ? "itzg/minecraft-bedrock-server" : "itzg/minecraft-server"}'
+  server_image: '${var.server_type == "bedrock" ? "itzg/minecraft-bedrock-server" : "itzg/minecraft-server"}'
   ext_port: '${var.server_type == "bedrock" ? 19132 : 25565}'
   server_protocol: '${var.server_type == "bedrock" ? "udp" : "tcp"}'
+  host_bind_dir:
+    value: /var/lib/docker/cloudcraft
+    description: "The path on the host instance to bind to the container's '/data' dir where all the world and other server state files are stored. Because the container optimized image limits '/var' in general with noexec, we store it under the docker working dir because it is stateful and allows execution. Refer to: https://cloud.google.com/container-optimized-os/docs/concepts/security#filesystem for details on the COS mount permissions."
 
 terraform:
   backend:
@@ -98,14 +101,14 @@ resource:
       
   # Permenant Minecraft disk, stays around when VM is off
   google_compute_disk:
-    minecraft_disk:
-      name: minecraft-disk
+    cloudcraft_disk:
+      name: cloudcraft-disk
       type: pd-standard
       zone: ${var.zone}
-      image: ${var.image}
+      image: ${var.host_image}
       size: 20
       lifecycle:
-        prevent_destroy: true
+        prevent_destroy: false #true
     
   # Permenant IP address, stays around when VM is off
   google_compute_address:
@@ -128,26 +131,54 @@ resource:
   
   # VM to run Minecraft, we use preemptable which will shutdown within 24 hours
   google_compute_instance:
-    minecraft_server:
-      description:
-      name: ${var.server_name}
+    cloudcraft_host:
+      description: Hosts the cloudcraft server container.
+      name: ${var.host_name}
       machine_type: ${var.machine_type}
       zone: ${var.zone}
       tags: ["minecraft", "ssh"]
       allow_stopping_for_update: true
-      # Run itzg/minecraft-server docker image on startup
-      # The instructions of https://hub.docker.com/r/itzg/minecraft-server/ are applicable
-      # For instance, Ssh into the instance and you can run
-      #  docker logs mc
-      #  docker exec -i mc rcon-cli
-      # Once in rcon-cli you can "op <player_id>" to make someone an operator (admin)
-      # Use 'sudo journalctl -u google-startup-scripts.service' to retrieve the startup script output
-      metadata_startup_script: "docker run -d -p ${local.ext_port}:${local.ext_port}/${local.server_protocol} -e EULA=TRUE -e VERSION=1.12.2 -v /var/minecraft:/data --name mc -e TYPE=FORGE -e FORGEVERSION=14.23.0.2552 -e MEMORY=3G --rm=true ${local.docker_image}:latest;"
+      metadata_startup_script: |
+        {
+          echo "Starting at $(date)"
+          mkdir -p ${local.host_bind_dir.value}
+          echo "
+        # credit to https://www.redhat.com/sysadmin/systemd-automate-recovery
+        # credit to https://gist.github.com/dotStart/ea0455714a0942474635
+        [Unit]
+        Description=cloudcraft-server
+        # Try 8 times, waiting 15 seconds in between each before giving up (2 min total)
+        StartLimitIntervalSec=15
+        StartLimitBurst=8
+        # Call cleanup script if necessary:
+        # OnFailure=my-app-recovery.service
+
+        [Service]
+        User=root
+        WorkingDirectory=/var/lib/docker
+        ExecStart=/bin/bash -c 'docker rm mc || true; \
+        docker run \
+          --detach \
+          --interactive \
+          --tty \
+          -p ${local.ext_port}:${local.ext_port}/${local.server_protocol} \
+          -e EULA=TRUE \
+          -e VERSION=LATEST \
+          -v ${local.host_bind_dir.value}:/data \
+          --name mc \
+          -e MEMORY=4G \
+          ${local.server_image}:latest >> /var/log/mc-docker-run.log 2>&1'
+        Restart=always
+        
+        [Install]
+        WantedBy=multi-user.target" > /etc/systemd/system/cloudcraft.service && systemctl enable cloudcraft && systemctl start cloudcraft
+        } >> /var/log/startup-script.log 2>&1
+      
       metadata:
         enable-oslogin: true
       boot_disk:
         auto_delete: false
-        source: minecraft-disk # google_compute_disk.minecraft_disk.self_link
+        source: "${google_compute_disk.cloudcraft_disk.self_link}"
       network_interface:
         network: "${google_compute_network.minecraft_network.id}"
         subnetwork: "${google_compute_subnetwork.minecraft_subnet.id}"
@@ -216,7 +247,7 @@ resource:
     switcher:
       project: ${var.project_id}
       zone: ${var.zone}
-      instance_name: "${google_compute_instance.minecraft_server.name}"
+      instance_name: "${google_compute_instance.cloudcraft_host.name}"
       role: "${google_project_iam_custom_role.minecraft_switcher.id}"
       members:
         - "group:${var.vm_managers}"
